### ISSUE TITLE
Loading from persistence raises KeyError in process_group

### ISSUE THREAD

**Issue by shadetree01010100** [nio-blocks/buffer#10]
block config:
```
{
    "backup_interval": {
        "days": 0,
        "microseconds": 0,
        "seconds": 3600
    },
    "group_by": null,
    "interval": {
        "days": 0,
        "microseconds": 0,
        "seconds": 1
    },
    "interval_duration": {
        "days": 0,
        "microseconds": 0,
        "seconds": 10
    },
    "load_from_persistence": true,
    "log_level": "NOTSET",
    "name": "new buffer",
    "signal_start": false,
    "type": "Buffer",
    "version": "0.1.0"
}
```

The first time the service runs it works as expected, but after stopping and restarting each signal received logs the following:
```
[2017-10-27 17:26:31.444] NIO [ERROR] [test_buffer.ThreadedPoolExecutorRouter] new buffer.process_signals failed
Traceback (most recent call last):
  File "c:\users\tom\nio\nio\nio\router\base.py", line 404, in notify_signals_to_block
    block_receiver.block.process_signals(signals)
  File "C:\Users\Tom\nio\projects\LOCAL\blocks\buffer\buffer_block.py", line 106, in process_signals
    self.for_each_group(self.process_group, signals)
  File "c:\users\tom\nio\nio\nio\block\mixins\group_by\group_by.py", line 80, in for_each_group
    result = target(group_sigs, group, *args, **kwargs)
  File "C:\Users\Tom\nio\projects\LOCAL\blocks\buffer\buffer_block.py", line 121, in process_group
    self._cache[key][now].extend(signals)
KeyError: 1509125191
```

Setting `"load_from_persistence": false` solved the problem, at the cost of persistence.

**Comment by shadetree01010100** [comment]
caused by safepickle 0.2.0 https://github.com/niolabs/safepickle/issues/11
